# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

# Ensure role dependencies are in place
if [ "up", "provision" ].include?(ARGV.first) && File.directory?("roles") &&
  !(File.directory?("roles/henriquemc.vagrant") || File.symlink?("roles/henriquemc.vagrant"))
  system("ansible-galaxy install --force -r requirements.txt -p roles")
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook-install-vagrant.yml"
    ansible.sudo = true
  end
end

